### ISSUE TITLE
Add height option

### ISSUE THREAD

**Issue by Saklad5** [eddieantonio/imgcat#10]
When using this command, you’d ideally want the image to be as large as possible without going offscreen. The width parameter works quite well for landscape images, but portrait images will still be too large. Adding equivalent functionality for height would be very useful.

**Comment by eddieantonio** [comment]
This is implemented as of [version 2.2.0](https://github.com/eddieantonio/imgcat/releases/tag/v2.2.0)!

If you're using Homebrew, simply type:

```sh
brew install eddieantonio/eddieantonio/imgcat
```
