### ISSUE TITLE
Add pipe support

### ISSUE THREAD

**Issue by jonathanwren** [eddieantonio/imgcat#13]
Being able to pipe in an image, rather than having to read from a saved file, would be a very useful feature addition to an already very useful tool. 

One use case that I've run into is trying reading thumbnail data from large file types (like Photoshop files). Using exiftool, it's easy to extract the thumbnail data from a Photoshop file, but I find myself having to save it to a temporary file in order to be able to view it. 

Currently, this process looks something like this:
```
exiftool -b -PhotoshopThumbnail example.psd > temp.jpg
imgcat temp.jpg
rm temp.jpg
```

But having something like this would be much more useful:

`exiftool -b -PhotoshopThumbnail example.psd | imgcat`

**Comment by eddieantonio** [comment]
Thanks for the interest in the project! This is something I've thought of implementing, but wasn't sure if it would even be useful. You've proved that it has! I hope to get cracking on this on Friday.

**Comment by eddieantonio** [comment]
This issue is fixed! It's available in imgcat 2.1.0, which you can install with Homebrew.

**Comment by jonathanwren** [comment]
Works like a charm. Thank you!

**Comment by rocaltair** [comment]
@jonathanwren try `imgcat <(exiftool -b -PhotoshopThumbnail example.psd)`

**Comment by jonathanwren** [comment]
@rocaltair That also worked. Thanks!
