### ISSUE TITLE
--width or -w arguments ignored in 2.1.0

### ISSUE THREAD

**Issue by matt-deboer** [eddieantonio/imgcat#15]
```
$> which imgcat
/usr/local/bin/imgcat

$> imgcat -v
imgcat 2.1.0

$> echo $TERM
xterm-256color
```
iterm2: build 3.1.5 

For all of these permutations, the image shows up in full-screen:

`imgcat -w 10 img.jpg`
`imgcat --width 10 img.jpg`
`imgcat --width 10--no-rescale img.jpg`

What am I doing wrong? How can I display a resized image?

**Comment by eddieantonio** [comment]
You are doing nothing wrong! It's just that scaling for iTerm's embedded image mode is not yet supported :/

When I get time to do some hobby programming, I'll be sure to fill in this gap in functionality!

**Comment by matt-deboer** [comment]
Ah, ok; thanks--I'll look forward to that.
Anyway, thanks for this cool utility.
