### ISSUE TITLE
During homebrew installation: "<<-EOS.undent is disabled"

### ISSUE THREAD

**Issue by xoxota99** [eddieantonio/imgcat#18]
During the initial install of imgcat (via HomeBrew), I received the following error message:

==> Installing imgcat from eddieantonio/eddieantonio
==> Downloading https://github.com/eddieantonio/imgcat/archive/v2.1.0.tar.gz
==> Downloading from https://codeload.github.com/eddieantonio/imgcat/tar.gz/v2.1
######################################################################## 100.0%
==> autoconf
==> ./configure
==> make install PREFIX=/usr/local/Cellar/imgcat/2.1.0
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/eddieantonio/homebrew-eddieantonio/imgcat.rb:25:in `caveats'
Please report this to the eddieantonio/eddieantonio tap!
Or, even better, submit a PR to fix it!

**Comment by eddieantonio** [comment]
Thanks for the issue report! Homebrew deprecated and removed that `#unindent` pretty darn quick, but it should be fixed now!
