### ISSUE TITLE
read from NULL while cat a bmp file

### ISSUE THREAD

**Issue by frokaikan** [eddieantonio/imgcat#20]
terminate called after throwing an instance of 'cimg_library::CImgArgumentException'
  what():  cimg::fread(): Invalid reading request of 0 unsigned char from file 0x7453a0 to buffer (nil).

[test.zip](https://github.com/eddieantonio/imgcat/files/2222334/test.zip)

**Comment by eddieantonio** [comment]
Thanks for the bug report!

It appears that `test.bmp` is malformed. It sets its width as 0, which breaks nearly every image program I try to open this in. However, changing the 32-bit little endian number at byte 0x12 to 32—the actual width—I get the attached result:

![fixed.bmp in imgcat](https://user-images.githubusercontent.com/2294397/43179264-202eeffe-8f8f-11e8-86d1-19641dd595b2.png)

[fixed.zip](https://github.com/eddieantonio/imgcat/files/2226457/fixed.zip)

---

While I don't think this is a bug in imgcat _per se_, it may be a bug in the library that imgcat uses—[CImg](https://github.com/dtschump/CImg). It crashes on bitmaps with width==0. I'll mark this as wontfix for this particular issue, but I do encourage you to fill a bug report for CImg, linking to this issue!
