### ISSUE TITLE
Build error under Ubuntu 18.10

### ISSUE THREAD

**Issue by psk-ixolit** [eddieantonio/imgcat#21]
Here is the build log: https://pastebin.com/HeSNdB2t

**Comment by eddieantonio** [comment]
Thanks for the build log! I'm reuploading it to GitHub issues, so I can use it to debug the build later.

Looks like some issues with how CImg library is interacting with the g++ settings.

[HeSNdB2t.txt](https://github.com/eddieantonio/imgcat/files/2501853/HeSNdB2t.txt)

**Comment by psk-ixolit** [comment]
This seems to be related: https://github.com/dtschump/CImg/issues/199

**Comment by psk-ixolit** [comment]
Updating CImg.h to the latest upstream release seems to fix the problem.

**Comment by eddieantonio** [comment]
Thanks! That did the trick! I updated to version 2.4.0.
