### ISSUE TITLE
trying to compile on manjoro

### ISSUE THREAD

**Issue by cyrstem** [eddieantonio/imgcat#23]
I'm having this issue:
++  src/imgcat.o src/rgbtree.o src/print_image.o src/load_image.o  -ljpeg -lpng  -ltermcap -lm -lpthread -o imgcat
/usr/bin/ld: cannot find -ltermcap
collect2: error: ld returned 1 exit status
make: *** [Makefile:51: imgcat] Error 1

**Comment by eddieantonio** [comment]
Hello! I don't use manjaro, but have you tried installing [libtermcap](https://aur.archlinux.org/packages/termcap/)? `imgcat` requires this package to figure out things about your terminal.

[It is even listed as one of the dependencies of the `imgcat` package on AUR](https://aur.archlinux.org/packages/imgcat-git/)!

**Comment by eddieantonio** [comment]
I'm closing this, since I'm pretty sure on Arch-based systems, you can use:

```
pacman -Syu imgcat
```

to install imgcat and its dependencies (e.g., `libtermcap`).

If you have any more difficulty, feel free to reopen!
