### ISSUE TITLE
Cannot open jpg files in macOS 10.15 + iTerm2 + Zsh

### ISSUE THREAD

**Issue by Zirconium-9** [eddieantonio/imgcat#29]
When I try to open a jpg file, it doesn't work and just show a broken icon.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/30790455/66985361-334c5000-f0ef-11e9-9de7-1c111df1c15d.png">
But works quite well when opening png files
<img width="566" alt="image" src="https://user-images.githubusercontent.com/30790455/66985395-4eb75b00-f0ef-11e9-9b96-e9dfc0085f2f.png">

**Comment by Zirconium-9** [comment]
It's weird that some jpg files can be opened, but some not.
Here is an example which cannot be correctly opened.
![63056792_p0](https://user-images.githubusercontent.com/30790455/66986957-5f1d0500-f0f2-11e9-9616-80721c2c08a1.jpg)

**Comment by Zirconium-9** [comment]
When I try to compile it with the newest [CImg.h,](https://github.com/dtschump/CImg/blob/48401328b01a5e036aca9aeab9d446332ce338ae/CImg.h) it looks like working well.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/30790455/66988001-647b4f00-f0f4-11e9-8b76-6a632d37507f.png">

**Comment by eddieantonio** [comment]
Hi! I am unable to reproduce this in iTerm 3.3.7beta1 with imgcat 2.3.0. I think this might be an underlying problem with iTerm2. Could you please update iTerm2? And confirm whether it works with iTerm2's image viewer, [confusing _also_ called `imgcat`](https://www.iterm2.com/utilities/imgcat) (but it's a shell script; not a C program).

**Comment by newtorn** [comment]
@Zirconium-9 That's your image file format problem, I can solve it by saving JPG image to PNG format through Python's PIL. I wrote a script named pyimgcat that calls imgcat on Iterm2:

![截屏2019-12-06下午1 26 34](https://user-images.githubusercontent.com/43400069/70299012-9eccb700-182e-11ea-9f48-0b316be92b1f.png)

pyimgcat script:
```python
def print_help():
    print('\nUsage python pyimgcat.py [file1...filen]\n')
    print('    file: file path or folder if file is a folder and \n' +
          '    it is first param then list its all.')
    print('\nExamples:')
    print('    for help: python pyimgcat.py')
    print('    for single: python pyimgcat.py same.jpg')
    print('    for list dir: python pyimgcat.py xxx/imgdir')
    print('    for list images: python pyimgcat.py 1.png 2.jpg 3.jpeg')
    print('\nOnly support on iTerm2 with imgcat tool, you can find it here:')
    print('    https://www.iterm2.com/documentation-utilities.html')
    print('\npyimgcat: you sholud install PIL library.')

def main():
    from tempfile import NamedTemporaryFile
    from PIL import Image
    import sys
    import os

    # Your iterm2 imgcat
    imgcat = os.path.join(os.environ['HOME'], '.iterm2/imgcat')

    if len(sys.argv) == 1:
        print_help()
        return

    ls = False
    path = sys.argv[1]
    if os.path.isdir(path):
        ls = True
        t = []
        for ld in os.listdir(path):
            if os.path.isfile(ld):
                t.append(ld)
        path = t
    else :
        path = [path]
        if len(sys.argv) > 2:
            ls = True
            for p in sys.argv[2:]:
                if os.path.isfile(p):
                    path.append(p)
            else:
                ls = False

    try:
        f = NamedTemporaryFile()
        for p in path:
            if os.path.exists(p):
                try:
                    img = Image.open(p)
                    img.save(f.name, format='png')
                    os.system('%s %s' %(imgcat, f.name))
                    if ls:
                        print(os.path.split(p)[1] + '\n')
                except:
                    pass
            else:
                print('pyimgcat: %s: No such file or directory'%p)
    except:
        if f is not None:
            f.close()


if __name__ == '__main__':
    main()

```

**Comment by Zirconium-9** [comment]
@newtorn I think it works pretty well! Thanks for your solution!
