### ISSUE TITLE
Not working with screen

### ISSUE THREAD

**Issue by paxperscientiam** [eddieantonio/imgcat#30]
Hello, `imgcat` is working for me on Catalina (not with jpg as someone else reported), but not over `screen`. When I try to use over `screen`, i just get the base64'd string.

Any idea what might be wrong? Thank you.

**Comment by eddieantonio** [comment]
Thanks for the issue report!

This is a limitation of how iTerm2's inline image protocol works and how tmux/screen work. See https://gitlab.com/gnachman/iterm2/issues/6799 for more details. Unfortunately, this is not something that can be fixed within this repo at the moment.

Perhaps uninstall this implementation of `imgcat` and use iTerm2's built-in implementation instead (in the toolbar, select iTerm2 » Install Shell Integration).

 :/
