### ISSUE TITLE
higher resolution images

### ISSUE THREAD

**Issue by netpipe** [eddieantonio/imgcat#44]
https://github.com/trashhalo/imgcat/issues/3

https://github.com/trashhalo/imgcat/commit/1f9ef8c888fa93e1eedc591115431bbd1897d944

double resolution by using half characters

**Comment by eddieantonio** [comment]
Half-height characters are already implemented by using the `-H` option:

    imgcat -H path/to/some/image.png

This feature was implemented 4 years ago: 4eace2bbbb85c85efa5be0578950c268aaf71474
