### ISSUE TITLE
Failed to open image

### ISSUE THREAD

**Issue by zacharywhitley** [eddieantonio/imgcat#45]
I'm getting the following error message trying to open an image

```imgcat: Failed to open image: yorkshire_terrier_9.jpg```

It doesn't appear to be a permission problem because I can do a hexdump on the file with `hexdump Yorkshire_terrier_9.jpg`. I doubt that the image is corrupted as it's part of a well known image dataset.

I've been able to correctly display images from another dataset but they were png's so I don't know if this problem is specific to jpgs.

**Comment by eddieantonio** [comment]
Hi @zacharywhitley. Could you run `file Yorkshire_terrier_9.jpg`? It's difficult debug this without more info :/

**Comment by zacharywhitley** [comment]
I should have included that I had run that command before. 

```file yorkshire_terrier_9.jpg```

```yorkshire_terrier_9.jpg: JPEG image data, JFIF standard 1.01```

If I convert the image with ```convert yorkshire_terrier_9.jpg yorkshire_terrier_9.png``` it displays correctly

```imgcat yorkshire_terrier_9.png```

Maybe I'm missing a library? I'll go back and check the built to make sure I didn't miss any errors or warnings

BTW, love the tool. It's been great for AI image sets where I'm often in a terminal and don't really care exactly what the image looks like but just want to get an idea that I'm looking at the right thing.

**Comment by zacharywhitley** [comment]
Aaaaaaaand there it is. Sorry about that. I had missed the following error when running ```./configure```

```checking to link with libjpeg [using jpeg_set_defaults()]... /usr/bin/ld: cannot find -ljpeg```

**Comment by eddieantonio** [comment]
That's okay! I don't know what system you're on, but you'll want to run either `sudo apt install libjpeg-dev` or `brew install libjpeg`

**Comment by zacharywhitley** [comment]
Thanks, and for anyone following along in the future. It was on Amazon Linux (which I think is based on RHEL). Installing libjpeg-turbo-devel did the trick.

```yum install libjpeg-turbo-devel```
