### ISSUE TITLE
Homebrew no formula

### ISSUE THREAD

**Issue by xieshuaix** [eddieantonio/imgcat#46]
When installing via brew, I got the following error:
![image](https://user-images.githubusercontent.com/22043680/113432169-7b5c5100-940f-11eb-8e15-92bc333a4ede.png)

How can I fix this? Thanks.
Home brew version:
![image](https://user-images.githubusercontent.com/22043680/113432294-b494c100-940f-11eb-9ddc-3c1287741ff1.png)

**Comment by eddieantonio** [comment]
Hello! I tried this last night and got the same results as in your screenshots. However, I tried it again today after using `brew update`; it's possible a previous brew update broke something and a more recent version fixed it.

Please run `brew update` and try it again! This is what I'm working with:

```
$ brew --version
Homebrew 3.0.10-215-gb1ad030
Homebrew/homebrew-core (git revision 818dd12b6c; last commit 2021-04-04)
Homebrew/homebrew-cask (git revision 83acf002cf; last commit 2021-04-03)
```

**Comment by eddieantonio** [comment]
I cannot reproduce this anymore; this works for me:

    brew install eddieantonio/eddieantonio/imgcat

If you can provide a way to reproduce this, I can reopen this issue, but I will close for now.
