### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by cocoonkid** [eddieantonio/imgcat#48]
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the trashhalo/brews tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/trashhalo/homebrew-brews/Formula/imgcat.rb:6
```

reference: https://apple.stackexchange.com/questions/429492/warning-calling-bottle-unneeded-is-deprecated-there-is-no-replacement

**Comment by eddieantonio** [comment]
Wrong `imgcat`! Please see https://github.com/trashhalo/imgcat/issues instead!

(there's at least 3 projects named `imgcat` — possibly more!)
