### ISSUE TITLE
Use of "-W 100%" Sometimes causes red hue to image 

### ISSUE THREAD

**Issue by hulleyrob** [eddieantonio/imgcat#53]
Tested on both pngs and jpegs.

<img width="558" alt="image" src="https://github.com/eddieantonio/imgcat/assets/17217514/57c2b67f-9d00-47df-a283-deb2bb410ec0">

<img width="1176" alt="image" src="https://github.com/eddieantonio/imgcat/assets/17217514/816d026a-ff34-4217-9a22-fd8aeb8f6e62">

Added original image not sure what more could I can do to help?

![Screen Shot 2022-06-12 at 12 17 58 pm](https://github.com/eddieantonio/imgcat/assets/17217514/7d305d1d-db52-4a74-b147-1e8003b025e0)

**Comment by hulleyrob** [comment]
Sorry about that I thought I had found the correct "source".

**Comment by eddieantonio** [comment]
No worries! It's... more confusing than it ought to be!
