### ISSUE TITLE
fail on grayscale image

### ISSUE THREAD

**Issue by byangderek** [eddieantonio/imgcat#9]
imgcat: src/load_image.cc:48: bool load_image(const char*, Image*, LoadOpts*): Assertion `(img.spectrum() == 3) || (img.spectrum() == 4)' failed.

**Comment by eddieantonio** [comment]
Thanks for reporting this! This is fixed in imgcat 2.0.1. If you installed using Homebrew, you can upgrade:

    brew upgrade imgcat
